# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160614_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Up_next',
            new_name='Step',
        ),
    ]
